spring:
  datasource:
    username: root
    password: root
    url: jdbc:mysql://172.20.10.4:3306/xingchenmall-pms
    driver-class-name: com.mysql.jdbc.Driver
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
  application:
    name: xingchenmall-product
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
  thymeleaf:
    cache: false
  redis:
    host: 172.20.10.4
    port: 6379

#    alicloud:
#      access-key:
#      secret-key:
#      oss:
#        endpoint:
mybatis-plus:
  mapper-locations: classpath*:/mapper/**/*.xml
  global-config:
    db-config:
      id-type: auto
      logic-delete-value: 1
      logic-not-delete-value: 0
server:
  port: 10000
logging:
  level:
    com.lcy.xingchenmall: error
